### ISSUE TITLE
Same artifacts as randomwalk SSS

### ISSUE THREAD

**Issue by RomboDev** [rgl-epfl/learned-subsurface-scattering#4]
Hi there,

great work ! More an head-up than a bug report. Did some testing to see if your impl would fix some artifacts present in the bruteforce approach but for what I see it just inherits them. That's about the unnatural darkening you see around the teeth of meatboy. 

 ciao, max

![meatboy_learnedsss_artifacts](https://user-images.githubusercontent.com/5871386/95632981-0d9a2280-0a87-11eb-8677-2368b146a4b2.png)

**Comment by dvicini** [comment]
Hi,

Thanks for trying out our method! These problems are not too surprising. Our approach in the end is limited by the representation power of its polynomial surface approximation. I wouldnt be surprised if these low-order polynomials are just not expressive enough to fit the teeth of the character.

We also have an implementation of a path tracer which works on the polynomial surfaces (i.e. it sidesteps the machine learning pipeline). You could try rendering with that and most likely it will give you the same artifacts. Just use the `ptracerpoly` technique instead of the ML model when you call the render script

Delio

**Comment by RomboDev** [comment]
Yep. I tried yours also because my volumetric randomwalk SSS was returning those artifacts too. However it's the same with Arnold, Cycles etc. A bit better with the dipole impl using disk based importance sampling but jeez that's so flat. Looks there's still room for advancements in state-of-the-art SSS.

Keep up the great work ! :)
Ciao, Max

[g=0 to speed up render]
![Screenshot from 2020-10-13 22-39-08](https://user-images.githubusercontent.com/5871386/95914325-d937a680-0da5-11eb-8839-72dbc7e3ae38.png)
![Screenshot from 2020-10-13 22-39-24](https://user-images.githubusercontent.com/5871386/95914350-e2287800-0da5-11eb-891d-480ca8ad6c74.png)

**Comment by dvicini** [comment]
Okay. I am not sure I understand. Random walk should be the ground truth, right? It might not always be visually pleasant, but path tracing should always give the right answer. If there is anything I've learned working on SSS, is that all the dipole methods have pretty huge issues everywhere.

Delio

**Comment by RomboDev** [comment]
Yeah we have two different problems here. One is the one you highlighted about your learned SSS approach, mine instead is about how random walk needs good geometry to work optimally.. the above model has full teeths modelled, meaning the back of the teeths is into the volume and when the randomwalk intersects that, it believes is on the outside of the model but being still into the volume.. trying to lookup light it gets back with black hence the unpleasant dark silhouette around the teeths.

Ciao, Max
